Make input & request function in AddFriendActivity
chatty-app/chatty-android pull request #106
Opened 2018-09-01 12:28 UTC by eastroots92

- EditText 리스너를 통해 입력 정보를 확인한다.
- 입력 완료 시 데이터들을 서버에 전송한다.

2018-09-01 13:55 UTC, eldenpark requested changes
:+1:

2018-09-01 13:55 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/presenter/addFriend/AddFriendPresenter.java
> +  public void validationCheckName(EditText editTextProfileName) {
`validateProfileName()`
method is named with verb infinitive

2018-09-01 13:55 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/presenter/addFriend/AddFriendPresenter.java
> +    boolean isRequest = PartnerAction.requestAddNewPartnerProfile(newPartnerRequest, profileImage);
첫째로, 현재의 상태 핸들링 설계에서 action을 이렇게 획득해오는 것은 혼란을 야기할 것 같습니다. Action은 StateManager로만 단 방향으로 전파되고, stateListener에서 변화한 상태 (reducer를 통해 boolean이 유통되겠지요) 를 들어서 이곳까지 전파해주는 것이 좋겠습니다.

둘째로, `isRequest` 로 이름하는 것보다 다르게 이름하는 것이 좋겠습니다. 이 boolean이 어떤 값을 의미하는지 짤막히 설명해주실 수 있나요?

2018-09-01 13:55 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/presenter/addFriend/AddFriendPresenter.java
> +        if(isProfile && isName) {
`if () {}`
if then whitespace

2018-09-01 13:55 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/state/action/PartnerAction.java
> +  public static boolean requestAddNewPartnerProfile(NewPartnerRequest newPartnerRequest, MultipartBody.Part file) {
param을 multiline으로 기재해주세요. char count 100이 넘어가는 것 같습니다.

2018-09-01 13:55 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/state/action/PartnerAction.java
> +          isSuccess[0] = true;
이곳에서는 예외없이 dispatch를 날려주시는 것이 좋겠습니다. 후에 이를 type으로 더 견고히 하겠습니다.

2018-09-01 13:55 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/view/addFriend/AddFriendActivity.java
> +  private void validationCheckForm() {
`validateForm()`

2018-09-01 13:55 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/view/addFriend/AddFriendActivity.java
> +    this.validationCheckForm();
최초 render는 initialRender()에, 이후 update함수는 `update-()` 로 이름하여 `update()`함수로부터 관리되게 하면 좋겠습니다.

2018-09-01 13:55 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/view/addFriend/AddFriendActivity.java
> +  public void activateSubmitButton(boolean isSubmitReady) {
`updateSubmitButton()`

2018-09-01 16:58 UTC, eastroots92 commented on app/src/main/java/com/chatty/android/chattyClient/presenter/addFriend/AddFriendPresenter.java
> +    boolean isRequest = PartnerAction.requestAddNewPartnerProfile(newPartnerRequest, profileImage);
## Answer1.
알겠습니다.

## Answer2.
`isRequest`의 기능은 `AddNewPartnerProfile(새로운 파트너를 서버에 등록)`이 서버에 제대로 전달 되었을 때 true를 받고  `isRequest`를 통해 이후 액션들(ex. 해당 페이지를 종료한다. SharedPreference내 프로필 관련 boolean을 변경한다 등.)을 처리하려고 했습니다.
이 부분에 있어서 변수명이 의미 전달이 잘 안되는 것 같아 더 나은 변수명을 생각해서 적용하겠습니다.
> 현재 AddFriendActivity에서  `boolean`과 `If문`을 자주 이용하는데 이로 인해 해당 Activity와 관련된 Presenter가 깔끔하지 못하다는 생각이 들었습니다.
> 이 PR 이후에 Image library 를 통해 이미지와 관련된  작업을 하고 해당 Activity와 관련된 모든 Flow가 완성 되면 한번 깔끔하게 정리하려고 했었습니다.

2018-09-01 16:58 UTC, eastroots92 commented on app/src/main/java/com/chatty/android/chattyClient/state/action/PartnerAction.java
> +  public static boolean requestAddNewPartnerProfile(NewPartnerRequest newPartnerRequest, MultipartBody.Part file) {
네!

2018-09-01 16:59 UTC, eastroots92 commented on app/src/main/java/com/chatty/android/chattyClient/state/action/PartnerAction.java
> +          isSuccess[0] = true;
알겠습니다.  적용하겠습니다.

2018-09-01 16:59 UTC, eastroots92 commented on app/src/main/java/com/chatty/android/chattyClient/view/addFriend/AddFriendActivity.java
> +    this.validationCheckForm();
적용하겠습니다.

2018-09-02 09:49 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/presenter/addFriend/AddFriendPresenter.java
> +    boolean isRequest = PartnerAction.requestAddNewPartnerProfile(newPartnerRequest, profileImage);
partner에 관한 정보를 획득해오는건가요? 그렇다면 `partner` 정도도 괜찮습니다.

2018-09-04 17:18 UTC, merged