Redesign diary detail view
chatty-app/chatty-android pull request #66
Opened 2018-07-25 12:13 UTC by dbwjd

item_diary.xml의 디테일을 수정함.

Fixed https://github.com/chatty-app/chatty-app/issues/12

2018-07-25 12:14 UTC, eldenpark requested changes

2018-07-25 12:14 UTC, eldeni commented on app/src/main/res/layout/item_diary.xml
> +    />
inline

2018-07-25 12:58 UTC, merged

2018-07-26 02:37 UTC, eastroots92 reviewed
👍

2018-07-26 02:37 UTC, eastroots92 commented on app/src/main/res/layout/item_diary.xml
> +  android:layout_margin="16dp">
margin 값에 이렇게 직접적으로 `16dp`를 넣는 것도 좋지만
`dimen.xml`에 상수로 등록을 하고 사용한다면 유사한 기능을 하는 Layout에서도 쉽게 적용하고 변경이 가능해서 더 좋을 것 같습니다.

> 아직 구체적인 Layout이 나오진 않아서 이 부분은 지금 바로 수정할 필요는 없다고 생각합니다 👍

2018-07-26 02:37 UTC, eastroots92 commented on app/src/main/res/layout/item_diary.xml
> +    android:layout_marginStart="8dp"
21번라인과 22번 라인에 각각 marginTop과 marginStart으로 상단과 왼쪽 부분에만 간격을 벌려준 이유가 무엇인지 알 수 있을까요?

2018-07-26 20:02 UTC, dbwjd commented on app/src/main/res/layout/item_diary.xml
> +    android:layout_marginStart="8dp"
전체적으로padding이 들어간 상태에서 글의 제목 아래내용을 담는 부분은 제목 TextView와시작부분과 위쪽 간격이 떨어져 있어 포함된 Layout이여서 벌려줬습니다.