Add reqest chatting layout
chatty-app/chatty-android pull request #67
Opened 2018-07-25 12:54 UTC by dbwjd

item_chat_entry_base 디자인을 수정함.
채팅창의 사용자가 답하는 item_chat_request_base 레이아웃을 추가함

2018-07-26 02:09 UTC, eldeni commented
@dbwjd conflict이 발생하고 있는데요, 기존에 web에서 squash를 종종 진행했었는데, local에서 git rebase이후, 단일 커밋으로 (squash) 해주시면 좋을 것 같습니다. 필요하시면 가이드 드리겠습니다.

2018-07-26 02:11 UTC, eldenpark requested changes

2018-07-26 02:11 UTC, eldeni commented on app/src/main/res/layout/item_chat_entry_base.xml
> +  >
inline

2018-07-26 10:03 UTC, JSpiner commented on app/src/main/res/layout/item_chat_entry_base.xml
> +      android:text="Yuyuyu"/>
(지나가다가 도움이 될것같아 남깁니다.)
`Yuyuyu` 텍스트가 화면에 잘 나오는지 확인을 위한 텍스트인것 같습니다.

이럴경우 `tools:text` 속성을 추천드립니다.
IDE design preview 화면에서는 `tools:text`에 설정된 값이 보이고,
실제 빌드된 파일에서는 노출되지 않아 view를 테스트할때 용이합니다.

그 외에도 `tools`에 좋은 속성이 여러개 있습니다.
http://gun0912.tistory.com/73

2018-07-26 10:03 UTC, JSpiner commented on app/src/main/res/layout/item_diary.xml
> +    android:layout_marginStart="8dp"
(지나가다가 도움이 될것같아 남깁니다.)
`marginStart` 속성과 `marginLeft` 속성이 혼용되어있는데 
혼용되어 사용하는 이유가 혹시 있을까요?

rtl ltr 지원을 위해서라면, `marginStart`가 좋지만
그보다 통일성이 더 중요한것같습니다!
별다른 이유가없다면 한가지 속성으로 통일하는게 좋을것같아요.

2018-07-26 10:03 UTC, JSpiner commented on app/src/main/res/layout/item_diary.xml
> +    android:fontFamily="sans-serif"
(지나가다가 도움이 될것같아 남깁니다.)

앱 내에서 사용하는 폰트는 주로 2~4개정도입니다.
공통으로 많이 사용될 가능성이 농후할것같은데 
string.xml에 상수로 적어놓는건 어떨까요?

2018-07-26 10:03 UTC, JSpiner commented on app/src/main/res/layout/item_chat_entry_base.xml
> +      android:textSize="@dimen/item_chat_entry_base_textview_contents_img_test_size"
(지나가다가 도움이 될것같아 남깁니다.)
값을 하드코딩하지 않고 상수로 뺀것, 좋은것같습니다 👍 

다만, 모든 상황마다 수치를 1:1 대응되는 상수로 만드는건 
조금 효율적이지 못할것같아요.

[구글 매터리얼 가이드](http://material.io) 에 나온 상수를 이용하거나,
공통되는 값끼리 묶어보는건 어떨까요?

아래는 제가 자주 쓰는 패턴인데 도움이 될것같아 남깁니다.

```xml
    <dimen name="space_x_small">8dp</dimen>
    <dimen name="space_small">12dp</dimen>
    <dimen name="space_median">16dp</dimen>
    <dimen name="space_large">20dp</dimen>
    <dimen name="space_x_large">24dp</dimen>
```

2018-07-26 20:27 UTC, YuChocopie commented on app/src/main/res/layout/item_chat_entry_base.xml
> +      android:textSize="@dimen/item_chat_entry_base_textview_contents_img_test_size"
아직 정확한 레이아웃이 나오기 전까지는 하드코딩을 하는 것으로 하였는데 좋은 방법인 것 같습니다!!

2018-07-27 02:41 UTC, eldeni commented on app/src/main/res/layout/item_chat_entry_base.xml
> +      android:text="Yuyuyu"/>
@JSpiner 좋은 정보입니다 👍

2018-08-01 11:00 UTC, closed without merging