Create Main header Layout
chatty-app/chatty-android pull request #75
Opened 2018-08-04 11:23 UTC by dbwjd

-변경된 레이아웃에 따라 새로운 item_main_header 레이아웃을 추가한다. 
- 9-Patch로 사용할 이미지를 추가한다.

2018-08-07 03:43 UTC, eldeni commented
`8014509` 이 pr에 포함되지 않았어야 할 commit 이 있습니다. 이것을 빼고 force push해주실 수 있으신가요?

2018-08-07 03:44 UTC, eldenpark requested changes
`8014509` 커밋을 제외해주세요

2018-08-07 16:38 UTC, eldenpark requested changes

2018-08-07 16:38 UTC, eldeni commented on app/src/main/res/values/dimen.xml
> +  <dimen name="SIZE_20">20dp</dimen>
alphabet order, numeric order 지켜주시면 좋겠습니다.
```
SIZE_20
SIZE_40
```

2018-08-07 16:38 UTC, eldeni commented on app/src/main/res/values/colors.xml
> +  <color name="colorAccent">#313759</color>
order
```
colorAccent
colorPrimary
...
```

2018-08-07 16:38 UTC, eldeni commented on app/src/main/res/layout/item_main_header.xml
> +    android:layout_marginEnd="@dimen/SIZE_20"
order

2018-08-07 16:38 UTC, eldeni commented on app/src/main/res/layout/item_main_header.xml
> +  android:layout_height="@dimen/HEIGHT_56"
order

2018-08-07 16:38 UTC, eldeni commented on app/src/main/res/values/colors.xml
> +  <color name="main_puple">#a766fe</color>
`puple` => `purple` 이나, order상 이 위치보다 더 상위에 있어야 합니다.

2018-08-07 16:38 UTC, eldeni commented
@dbwjd commit 빼서 force push하셨네요. :+1:

2018-08-08 00:50 UTC, eastroots92 reviewed
👍

2018-08-10 10:01 UTC, eastroots92 approved these changes
:+1:

2018-08-10 10:03 UTC, merged