Redesign global_header
chatty-app/chatty-android pull request #76
Opened 2018-08-04 12:16 UTC by dbwjd

- item_global_header을 ConstraintLayout을 사용하여 변경사항에 맞게 수정한다.

2018-08-07 03:45 UTC, eldeni commented
여담이지만, item_global_header의 경우 `item_global_header` 으로 쓰면 가독이 더 좋습니다.

2018-08-07 03:45 UTC, eldeni commented
`8014509` 제외부탁드립니다. @dbwjd

2018-08-07 16:41 UTC, eldenpark requested changes

2018-08-07 16:41 UTC, eldeni commented on app/src/main/res/layout/item_global_header.xml
> +  android:layout_height="@dimen/HEIGHT_56"
order

2018-08-07 16:41 UTC, eldeni commented on app/src/main/res/layout/item_global_header.xml
> +<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
`props` 가 2개 이상일 때는, inline으로 적지 않아주시면 좋겠습니다.
`xmlns...` 는 다음 줄에 옴이 좋겠습니다.

2018-08-07 16:41 UTC, eldeni commented on app/src/main/res/layout/item_global_header.xml
> +    android:layout_marginStart="@dimen/SIZE_20"
order

2018-08-07 16:41 UTC, eldeni commented on app/src/main/res/layout/item_global_header.xml
> +    android:gravity="center"
order

2018-08-07 16:41 UTC, eldeni commented on app/src/main/res/layout/item_global_header.xml
> +    android:layout_alignParentRight="true"
order

2018-08-07 16:41 UTC, eldeni commented on app/src/main/res/values/colors.xml
> +  <color name="colorAccent">#313759</color>
이 변화 전 커밋에도 반영하지 않으셨나요?

2018-08-07 16:42 UTC, eldeni commented
이전 커밋에 했던 동일한 변화가 일부 보이는데요. 작업하시다보면 이런일이 이따금 발생할 수 있습니다. (패닉하지는 마시고요)

전 작업 merge하고, rebase하시면서 conflict을 해결하셔야 할 것으로 사료됩니다.

2018-08-08 01:03 UTC, eastroots92 requested changes
:+1: :+1:

2018-08-08 01:03 UTC, eastroots92 commented on app/src/main/res/layout/item_global_header.xml
> +    android:layout_width="@dimen/SIZE_108"
`item_global_header.xml`의 경우에는  Write Activity 뿐만 아니라 범용적이게 이곳저곳에서 사용되고 해당 `TextView`에 title 내용이 들어갈 것으로 생각 되는데 해당 부분에 108dp로 강제한다면 zeplin의 [`Add question`](https://app.zeplin.io/project/5b378a9304a78518248e08f3/screen/5b688341008a822d0c47f3a4) 과 같이 title 내용이 길어질 경우 우려사항이 있어 보입니다. 보다 넓게 width요소를 주거나 `match_parent`를 할당하는 것이 좋아 보입니다.

2018-08-08 01:03 UTC, eastroots92 commented on app/src/main/res/layout/item_global_header.xml
> +    android:layout_width="@dimen/SIZE_108"
#### match_parent
ConstraintLayout의 경우에는 `match_parent`를 지원하지 않는 것으로 알고 있습니다. `0dp`를 `match_parent`처럼 사용하시면 됩니다.
> ConstraintLayout내 손자의 경우에는 `match_parenrt`사용이 가능하나 자식에서는 사용 불가능한 것으로 알고 있습니다. [참고 자료](https://stackoverflow.com/questions/37603751/set-width-to-match-constraints-in-constraintlayout)

2018-08-10 11:11 UTC, eastroots92 reviewed
:+1:

2018-08-10 11:11 UTC, eastroots92 approved these changes
:+1:

2018-08-10 11:14 UTC, closed without merging