Upload ImageFile
chatty-app/chatty-android pull request #82
Opened 2018-08-16 15:31 UTC by dbwjd

아이콘 이미지파일 업로드

2018-08-17 03:52 UTC, eldeni commented
@dbwjd 파일명, 
![image](https://user-images.githubusercontent.com/13134658/44246978-2fd3e500-a21c-11e8-9cdd-689065b1efba.png)
중간에 띄어쓰기가 있는것인가요? 만약 있다면 없어져야 합니다.

또한, underline표기하시려면 capital letter를 떼주심이 좋을 것 같습니다.

`Foo_Bar` => `foo_bar`

2018-08-17 03:52 UTC, eldenpark requested changes
https://github.com/chatty-app/chatty-android/pull/82#issuecomment-413750193

2018-08-19 08:35 UTC, eldenpark requested changes
`app/src/main/res/drawable/Icon_Done.svg`

파일명 변경하신 거 맞나요? 만약 변경하였는데, case 만 바뀐이후로 git이 track을 못한 것이라면 방법을 알려드리겠습니다.

2018-08-19 08:38 UTC, closed without merging

2018-08-19 08:39 UTC, dbwjd commented
drawable에 svg확장자가 들어갈 수 없어 새 라이브러리를 만들어 다시 저장하겠습니다