Make setFriend function
chatty-app/chatty-android pull request #95
Opened 2018-08-25 08:49 UTC by eastroots92

2018-08-27 11:32 UTC, eldenpark requested changes

2018-08-27 11:32 UTC, eldeni commented on app/src/main/AndroidManifest.xml
> +
empty line

2018-08-27 11:32 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/state/action/PartnerAction.java
> +            PartnerProfileDetailEntry partnerProfile = new PartnerProfileDetailEntry(
여기서 business object로 변환하지 않고, hashMap으로 그대로 plain하게 넘기는 걸 권장드립니다.

2018-08-27 11:32 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/state/reducers/Reducers.java
> +        PartnerProfileDetailEntry partnerProfileDetailEntry = (PartnerProfileDetailEntry) action.getPayload().get("partnerProfileDetail");
reducer내에서 매 액션마다 새로운 인스턴스가 생성되어야 합니다. 그래야 view가 `diff()` 를 통해 state가 변화하였는지 알 수 있습니다. action에서 PartnerProfileDetailEntry를 만들지 말고 여기서 만드는 것이 좋겠습니다.

2018-08-27 12:27 UTC, eastroots92 commented
@eldeni  @dbwjd  말씀해주신 부분들 수정했습니다. 확인 부탁드립니다.

2018-08-27 12:59 UTC, eldenpark requested changes

2018-08-27 12:59 UTC, eldeni commented on app/src/main/AndroidManifest.xml
> +      android:clearTaskOnLaunch="true"/>
alphabetical order

2018-08-27 12:59 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/model/PartnerProfileDetailEntry.java
> +  public PartnerProfileDetailEntry(int id, String profileImage, String name, String bio, int diaryCount, int daysTogether, String createDate) {
width 100 이 넘어가는 것으로 보이는데요, 가독에 좋지 않습니다. 
매개변수 3개를 초과 (4부터) 는 multiline으로 적어주시면 좋겠습니다.

2018-08-27 12:59 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/state/reducers/Reducers.java
> +  private static PartnerProfileDetailEntry changePartnerProfile(PartnerProfileDetailResponse partnerProfileDetailResponse) {
이 메소드명은 `make-()` 가 좋겠습니다. not change-

2018-08-27 12:59 UTC, eldeni commented on app/src/main/res/layout/activity_friends_setting.xml
> +    style="?android:attr/borderlessButtonStyle"
inline

2018-08-27 12:59 UTC, eldeni commented on app/src/main/res/layout/activity_friends_setting.xml
> +
remove empty line

2018-08-27 12:59 UTC, eldeni commented on app/src/main/res/layout/activity_friends_setting.xml
> +
remove empty line

2018-08-27 12:59 UTC, eldeni commented on app/src/main/res/layout/activity_friends_setting.xml
> +    />
inline

2018-08-27 12:59 UTC, eldeni commented on app/src/main/res/layout/activity_friends_setting.xml
> +
empty line

2018-08-27 12:59 UTC, eldeni commented on app/src/main/res/layout/activity_friends_setting.xml
> +    />
inline

2018-08-27 12:59 UTC, eldeni commented on app/src/main/res/layout/activity_friends_setting.xml
> +
empty line

2018-08-27 12:59 UTC, eldeni commented on app/src/main/res/layout/activity_friends_setting.xml
> +
empty line

2018-08-27 12:59 UTC, eldeni commented on app/src/main/res/layout/activity_friends_setting.xml
> +
empty line

2018-08-27 12:59 UTC, eldeni commented on app/src/main/res/layout/activity_friends_setting.xml
> +
empty line

2018-08-27 12:59 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/view/setting/SettingActivity.java
> +    headerRender();
verb + object

`renderHeader()`

2018-08-27 12:59 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/view/setting/SettingActivity.java
>      buttonRender();
상동

2018-08-27 12:59 UTC, eldeni commented on app/src/main/AndroidManifest.xml
>      <activity android:name=".view.setting.SettingActivity"
new line

2018-08-27 12:59 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/state/action/PartnerAction.java
> +          public void onResponse(Call<PartnerProfileDetailResponse> call, Response<PartnerProfileDetailResponse> response) {
width 100이 넘는 것으로 보이는데요, multiline으로 기재가능할까요?

2018-08-27 12:59 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/state/action/PartnerAction.java
> +//        TODO: 서버와 연결 후에는 아래의 getDummyProfileDetail() 메서드와 관련된 코드들을 모두 지울 것
이 라인은 인덴트가 inconsistent합니다

2018-08-29 02:06 UTC, eldenpark requested changes

2018-08-29 02:06 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/state/action/PartnerAction.java
> +          public void onResponse(Call<PartnerProfileDetailResponse> call, Response<PartnerProfileDetailResponse> response) {
```java
public void onR(
  a,
  b
) {
  ...
}
```

2018-08-29 10:04 UTC, eastroots92 commented on app/src/main/java/com/chatty/android/chattyClient/state/action/PartnerAction.java
> +          public void onResponse(Call<PartnerProfileDetailResponse> call, Response<PartnerProfileDetailResponse> response) {
아... 멍청이 ㅠㅠ

2018-08-29 11:31 UTC, eldeni commented
code freeze. Could you squash all these commits into one? @eastroots92

2018-08-29 11:38 UTC, eastroots92 commented
@eldeni  yeah!!!!

2018-08-29 11:51 UTC, merged