Make Diary to show asynchronously loaded content
chatty-app/chatty-android pull request #96
Opened 2018-08-27 11:31 UTC by dbwjd

- Diary에서 비동기로 데이터 더미를 받아 넣어준다

https://github.com/chatty-app/chatty-app/issues/48

2018-08-27 12:21 UTC, eldenpark requested changes

2018-08-27 12:21 UTC, eldenpark commented on app/src/main/java/com/chatty/android/chattyClient/model/Diary.java
> +}
ALWAYS ending with new empty line

2018-08-27 12:21 UTC, eldenpark commented on app/src/main/java/com/chatty/android/chattyClient/model/Diary.java
>    public String getProfileImage() {
`/*`

기획은 되었으나, 아직 구현하지 않은 것이기 때문에 주석처리 해 놓은 의도를 이해할 수 있습니다. 후에는 꼭 주석화 해놓지 않고, 필요한 양만 코딩을 해도 되겠습니다.

또한, 주석화 하려면 여기서 부터 들어가는 것이 좋겠습니다. `/*public String ...`

2018-08-27 12:21 UTC, eldenpark commented on app/src/main/java/com/chatty/android/chattyClient/presenter/diaryDetail/DiaryDetailPresenter.java
> +    ArrayList<Diary> diarie = StateManagerWrapper.getState().getDiary();
`diaries`

2018-08-27 12:21 UTC, eldenpark commented on app/src/main/java/com/chatty/android/chattyClient/view/diaryDetail/DiaryDetailActivity.java
> +//    loadDependencies();
`loadDependencies()` 는 삭제되어도 좋겠습니다.

2018-08-27 12:21 UTC, eldenpark commented on app/src/main/java/com/chatty/android/chattyClient/view/diaryDetail/DiaryDetailActivity.java
> +//    setDummyData();
삭제

2018-08-27 12:21 UTC, eldenpark commented on app/src/main/java/com/chatty/android/chattyClient/view/diaryDetail/DiaryDetailActivity.java
> +//    initHeader();
remove

2018-08-27 12:21 UTC, eldenpark commented on app/src/main/java/com/chatty/android/chattyClient/view/diaryDetail/DiaryDetailActivity.java
> +//
이 부분 주석은 없어도 될 것 같습니다.

2018-08-27 12:21 UTC, eldenpark commented on app/src/main/java/com/chatty/android/chattyClient/state/action/DiaryAction.java
> +            ArrayList<Diary> dummyEntries = new ArrayList<>();
여기서 business class object로 변환하지 않고, reducer에서 해주세요. reducer에서 새로운 reference가 생성되야 합니다.

2018-08-29 11:17 UTC, eastroots92 commented on app/src/main/java/com/chatty/android/chattyClient/model/Diary.java
> +
이 부분에서 불필요한 주석과 빈 라인은 제거해 주는 것이 보기 더 좋을 것 같아요.

2018-08-29 11:17 UTC, eastroots92 commented on app/src/main/java/com/chatty/android/chattyClient/model/Diary.java
> +
이 부분도 위와 같이 빈 라인은 제거해 주는 것이 더 보기 좋아보입니다.

2018-08-29 11:17 UTC, eastroots92 commented on app/src/main/java/com/chatty/android/chattyClient/model/State.java
> +
이 부분도 번거로우시겠지만 함께 지워주시면 좋을 것 같아요

2018-08-31 07:31 UTC, eldenpark requested changes

2018-08-31 07:31 UTC, eldeni commented on app/src/main/java/com/chatty/android/chattyClient/presenter/diaryDetail/DiaryAdapter.java
> +}
end with empty line

2018-08-31 07:32 UTC, eldeni commented
commit message 수정 요청드립니다.
`Make Diary show asynchronously loaded content`
(without `wip`, no `to`) @dbwjd

2018-08-31 11:50 UTC, merged